from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "notebooks/workflows/03_colab_exact_dna_hurdler_designer.ipynb"


def _payload():
    return json.loads(NOTEBOOK.read_text())


def test_exact_dna_colab_is_output_free_hidden_and_stably_named():
    payload = _payload()
    assert payload["nbformat"] == 4
    assert "colab" not in payload.get("metadata", {})
    assert "widgets" not in payload.get("metadata", {})
    identifiers = []
    for cell in payload["cells"]:
        if cell["cell_type"] != "code":
            continue
        identifier = cell["metadata"]["id"]
        identifiers.append(identifier)
        assert cell["id"] == identifier
        assert cell["metadata"]["cellView"] == "form"
        assert cell["metadata"]["jupyter"]["source_hidden"] is True
        assert "".join(cell["source"]).startswith("#@title ")
        assert cell["outputs"] == []
        assert cell["execution_count"] is None
        compile("".join(cell["source"]), f"<{identifier}>", "exec")
    assert len(identifiers) == len(set(identifiers))


def test_exact_dna_colab_native_forms_and_runtime_selectors_are_present():
    text = NOTEBOOK.read_text()
    sources = {
        cell["metadata"]["id"]: "".join(cell["source"])
        for cell in _payload()["cells"]
        if cell["cell_type"] == "code"
    }
    parameters = set(
        re.findall(
            r"^([A-Za-z_]\w*)\s*=.*#@param",
            sources["exact-dna-input-form"] + sources["exact-dna-search-form"],
            re.MULTILINE,
        )
    )
    assert parameters >= {
        "input_mode",
        "sequence_id",
        "repeat_unit",
        "optional_spacer",
        "repeat_copies",
        "complete_exact_dna_or_fasta",
        "max_purchase_bp",
        "max_search_states",
        "search_timeout_seconds",
        "maximum_complete_routes_per_group",
        "route_confirmation_mode",
        "auto_download_results_zip",
    }
    selector = sources["exact-dna-re-plasmid-selection"]
    assert "Select all" in selector and "Select none" in selector
    assert "site_i_boxes" in selector and "site_ii_boxes" in selector
    assert "site_iii_boxes" in selector
    assert "plasmid_boxes" in selector
    assert 'checkbox_panel(site_i_names, "Site I enzymes — all selected")' in selector
    assert 'checkbox_panel(site_ii_names, "Site II enzymes — all selected")' in selector
    assert 'checkbox_panel(site_iii_names, "Site III adapter enzymes — all selected")' in selector
    assert '{"AflII"}' not in selector and '{"ApaI"}' not in selector
    query = sources["exact-dna-query-and-confirm"]
    assert "run_query()" in query
    assert "Confirm selected route" in query
    assert "query_exact_dna" in query
    assert "pair_dropdown" in query and "plasmid_dropdown" in query
    assert "scheme_dropdown" in query and "route_dropdown" in query
    assert "select_and_confirm_top_route" in query
    assert 'route_confirmation_mode == "Automatically use top-ranked route"' in query
    assert "Stepwise plasmid / insert viewer" in query
    assert "CircularGraphicRecord" in sources["exact-dna-engine"]
    assert "_prepare_exact_viewer(preview, preview_only=True)" in query
    assert "viewer_step" in query and "viewer_molecule" in query
    assert "viewer_view" in query and "viewer_range" in query
    assert "Focus cloning region" in query
    export = sources["exact-dna-idt-export"]
    upload = sources["exact-dna-idt-upload"]
    code_ids = [
        cell["metadata"]["id"]
        for cell in _payload()["cells"]
        if cell["cell_type"] == "code"
    ]
    assert code_ids[:2] == ["exact-dna-bootstrap", "exact-dna-idt-upload"]
    assert "files.upload()" in upload
    assert "64 * 1024" in upload
    assert "get_access_token()" in upload
    assert "screen_gblock_sequences" in upload
    assert "credential_payload = b\"\"" in upload
    assert "IDT_GBLOCK_ONLY_PURCHASE_POLICY" in query
    assert "confirm_best_exact_dna_route" in export
    assert "tempfile.TemporaryDirectory" in export
    assert "write_exact_dna_minimal_outputs" in export
    assert 'destination / "cloning_steps.csv"' in export
    assert "purchase_inserts.fasta" not in export  # generated by the package API
    assert "clear_idt_secret_environment()" in export
    assert "files.download" in export
    assert "Optional validation details" in export
    assert "idt_score_history_rows" in sources["exact-dna-engine"]
    assert "plot_idt_score_trajectory" in sources["exact-dna-engine"]
    assert 'event.status == "fragment_scored"' in export
    assert "idt_score_events.append(asdict(event))" in export
    assert "route_attempt" in export and "padding_variant" in export
    assert "rule_scores" in export and "positive_rules" in export
    assert "Final selected purchase gBlocks" in export
    assert "used_in_steps" in export and "reused" in export
    assert "_prepare_exact_viewer(result, preview_only=False)" in export
    assert "run_validation()" in export
    assert "auto_download_results_zip" in export
    assert "idt_validation_choice" not in text
    assert "credential_upload = widgets.FileUpload" not in text
    assert "IDT_CLIENT_SECRET=" not in text
    assert "IDT_PASSWORD=" not in text


def test_exact_dna_colab_generator_is_the_single_source_of_truth():
    generator = (ROOT / "scripts/generate_exact_dna_colab.py").read_text()
    assert "03_colab_exact_dna_hurdler_designer.ipynb" in generator
    assert "RF00059" in generator
    assert "cellView" in generator
    assert "source_hidden" in generator
    assert "force_fresh_clone = True" in generator
    assert '"checkout", "--force", "-B", repository_ref, "FETCH_HEAD"' in generator
    assert 'module_name.startswith("hurdler.")' in generator
    assert "for candidate in (Path.cwd(), *Path.cwd().parents)" in generator


def test_readme_links_exact_dna_colab_and_notebook_index():
    readme = (ROOT / "README.md").read_text()
    index = (ROOT / "notebooks/README.md").read_text()
    relative = "notebooks/workflows/03_colab_exact_dna_hurdler_designer.ipynb"
    assert relative in readme
    assert relative in index
    assert "colab.research.google.com" in readme
