"""Annotation-aware circular plasmid references and MCS cut schemes.

The committed JSON generated by this module is the authority used by the v2
designer.  Raw SnapGene files are deliberately not committed: they are parsed
in a temporary directory and reduced to sequence hashes and normalized feature
intervals.  Coordinates in the public models are zero-based, half-open.
"""

from __future__ import annotations

import hashlib
import json
import tempfile
import urllib.parse
import urllib.request
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from Bio import Restriction, SeqIO
from Bio.Seq import Seq
from Bio.SeqFeature import CompoundLocation

from .io import utc_now, write_json_atomic
from .paths import ProjectPaths


PLASMID_REFERENCE_VERSION = "vector-aware-hurdler-v2"
PLASMID_REFERENCE_FILENAME = "plasmid_reference_v2.json"
PLASMID_SCHEME_FILENAME = "plasmid_cut_schemes_v2.csv"


@dataclass(frozen=True)
class PlasmidSource:
    provider: str
    accession: str
    url: str
    downloaded_at: str
    sha256: str


@dataclass(frozen=True)
class PlasmidFeature:
    feature_id: str
    feature_type: str
    label: str
    intervals: tuple[tuple[int, int], ...]
    strand: int
    sources: tuple[str, ...]
    protected: bool
    feature_class: str

    @property
    def start(self) -> int:
        return min(value[0] for value in self.intervals)

    @property
    def end(self) -> int:
        return max(value[1] for value in self.intervals)


@dataclass(frozen=True)
class PlasmidReference:
    reference_id: str
    display_name: str
    sequence: str
    sequence_sha256: str
    circular: bool
    features: tuple[PlasmidFeature, ...]
    sources: tuple[PlasmidSource, ...]


@dataclass(frozen=True)
class PlasmidProfile:
    profile_id: str
    reference_id: str
    expression_strand: int
    mcs_start: int
    mcs_end: int
    legacy_left_enzyme: str
    legacy_right_enzyme: str
    notes: str = ""


@dataclass(frozen=True)
class CutterSite:
    side: str
    location: str
    canonical_enzyme: str
    enzyme_aliases: tuple[str, ...]
    recognition_site: str
    oriented_start: int
    oriented_end: int
    physical_start: int
    physical_end: int
    top_cut_oriented: int
    bottom_cut_oriented: int
    overhang_length: int
    outside_mcs_occurrences: int


@dataclass(frozen=True)
class VectorCutScheme:
    scheme_id: str
    profile_id: str
    left_location: str
    right_location: str
    left_cutter: CutterSite | None
    right_cutter: CutterSite | None
    valid: bool
    invalid_reason: str
    retained_backbone_sequence: str
    removed_arc_sequence: str
    left_restoration_sequence: str
    right_restoration_sequence: str
    retained_backbone_sha256: str


@dataclass(frozen=True)
class SilencingDecision:
    side: str
    allowed: bool
    status: str
    reason: str
    overlapping_features: tuple[str, ...] = ()
    donor_only_required: bool = True
    stop_rescue_sequence: str = ""


@dataclass(frozen=True)
class PlasmidReferenceDatabase:
    schema_version: str
    generated_at: str
    references: tuple[PlasmidReference, ...]
    profiles: tuple[PlasmidProfile, ...]
    schemes: tuple[VectorCutScheme, ...]

    def reference(self, reference_id: str) -> PlasmidReference:
        return next(item for item in self.references if item.reference_id == reference_id)

    def profile(self, profile_id: str) -> PlasmidProfile:
        return next(item for item in self.profiles if item.profile_id == profile_id)

    def schemes_for(self, profile_id: str) -> tuple[VectorCutScheme, ...]:
        return tuple(item for item in self.schemes if item.profile_id == profile_id)


# Public SnapGene resource identifiers.  pET-28a has two logical profiles.
REFERENCE_SPECS: dict[str, dict[str, str]] = {
    "pGEX-4T-1": {"set": "pgex_vectors_(ge_healthcare)", "plasmid": "pGEX-4T-1", "fasta": "pGEX-4T-1.fa", "ncbi": "U13853"},
    "pMAL-c5X": {"set": "basic_cloning_vectors", "plasmid": "pMAL-c5X", "fasta": "pMAL-c5X.fa", "ncbi": ""},
    "pET-21a(+)": {"set": "pet_and_duet_vectors_(novagen)", "plasmid": "pET-21a(+)", "fasta": "pET-21a(+).fa", "ncbi": ""},
    "pET-28a(+)": {"set": "pet_and_duet_vectors_(novagen)", "plasmid": "pET-28a(+)", "fasta": "pET-28a(+).fa", "ncbi": ""},
    "pCold_I": {"set": "basic_cloning_vectors", "plasmid": "pCold_I", "fasta": "pCold_I.fa", "ncbi": "AB186388"},
    "pUC18": {"set": "basic_cloning_vectors", "plasmid": "pUC18", "fasta": "pUC18.fa", "ncbi": "L09136"},
    "pQE-3": {"set": "qiagen_vectors", "plasmid": "pQE-3", "fasta": "pQE-3.fa", "ncbi": ""},
}


# MCS coordinates are from the public SnapGene feature named "MCS".  Profiles
# express the biological direction, not the arbitrary GenBank forward strand.
PROFILE_SPECS: tuple[dict[str, Any], ...] = (
    {"profile_id": "pGEX-4T-1", "reference_id": "pGEX-4T-1", "expression_strand": 1, "mcs_start": 929, "mcs_end": 966, "legacy_left_enzyme": "BamHI", "legacy_right_enzyme": "EagI"},
    {"profile_id": "pMAL-c5X", "reference_id": "pMAL-c5X", "expression_strand": 1, "mcs_start": 2683, "mcs_end": 2762, "legacy_left_enzyme": "NdeI", "legacy_right_enzyme": "HindIII"},
    {"profile_id": "pET-21a(+)", "reference_id": "pET-21a(+)", "expression_strand": -1, "mcs_start": 157, "mcs_end": 203, "legacy_left_enzyme": "NdeI", "legacy_right_enzyme": "XhoI"},
    {"profile_id": "pET-28a(+)", "reference_id": "pET-28a(+)", "expression_strand": -1, "mcs_start": 157, "mcs_end": 203, "legacy_left_enzyme": "BamHI", "legacy_right_enzyme": "XhoI"},
    {"profile_id": "pET-28a(+)_start_codon", "reference_id": "pET-28a(+)", "expression_strand": -1, "mcs_start": 157, "mcs_end": 203, "legacy_left_enzyme": "NcoI", "legacy_right_enzyme": "XhoI", "notes": "Shares sequence and annotations with pET-28a(+); NcoI overlaps the annotated start codon."},
    {"profile_id": "pCold_I", "reference_id": "pCold_I", "expression_strand": 1, "mcs_start": 300, "mcs_end": 360, "legacy_left_enzyme": "NdeI", "legacy_right_enzyme": "BspMI"},
    {"profile_id": "pUC18", "reference_id": "pUC18", "expression_strand": -1, "mcs_start": 398, "mcs_end": 455, "legacy_left_enzyme": "EcoRI", "legacy_right_enzyme": "HindIII"},
    {"profile_id": "pQE-3", "reference_id": "pQE-3", "expression_strand": 1, "mcs_start": 120, "mcs_end": 146, "legacy_left_enzyme": "BamHI", "legacy_right_enzyme": "HindIII"},
)


def bundled_plasmid_reference_path() -> Path:
    return ProjectPaths.discover().root / "data" / "reference_output" / PLASMID_REFERENCE_FILENAME


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _sha256_sequence(value: str) -> str:
    return _sha256_bytes(value.upper().encode("ascii"))


def _download(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "HURDLER/0.6 annotation materializer"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def _location_intervals(location: Any) -> tuple[tuple[int, int], ...]:
    parts = location.parts if isinstance(location, CompoundLocation) else (location,)
    return tuple((int(part.start), int(part.end)) for part in parts)


def _feature_label(feature: Any) -> str:
    qualifiers = feature.qualifiers
    for key in ("label", "gene", "product", "note", "name"):
        value = qualifiers.get(key)
        if value:
            return str(value[0] if isinstance(value, list) else value).strip()
    return str(feature.type)


def _feature_class(feature_type: str, label: str) -> str:
    text = f"{feature_type} {label}".lower().replace("_", " ")
    if "mcs" in text or "multiple cloning" in text:
        return "mcs"
    if "ribosome" in text or "rbs" in text or "shine" in text:
        return "rbs"
    if "start codon" in text or label.strip().upper() == "ATG":
        return "start_codon"
    if "stop codon" in text or "stop codons" in text:
        return "stop_codon"
    if "promoter" in text:
        return "promoter"
    if "operator" in text:
        return "operator"
    if "terminator" in text:
        return "terminator"
    if "origin" in text or "ori" == label.lower().strip():
        return "origin"
    if feature_type.lower() == "cds" or any(token in text for token in (" ampr", " kanr", "cmr", "lacz", "laci")):
        return "cds"
    return "functional"


def _normalize_record_features(record: Any, provider: str) -> list[PlasmidFeature]:
    rows: list[PlasmidFeature] = []
    for ordinal, feature in enumerate(record.features):
        if feature.type.lower() == "source" or feature.location is None:
            continue
        label = _feature_label(feature)
        feature_class = _feature_class(str(feature.type), label)
        intervals = _location_intervals(feature.location)
        strand = int(feature.location.strand or 0)
        rows.append(
            PlasmidFeature(
                feature_id=f"{provider}:{ordinal}",
                feature_type=str(feature.type),
                label=label,
                intervals=intervals,
                strand=strand,
                sources=(provider,),
                protected=feature_class != "mcs",
                feature_class=feature_class,
            )
        )
    return rows


def _merge_features(features: Iterable[PlasmidFeature]) -> tuple[PlasmidFeature, ...]:
    merged: dict[tuple[Any, ...], PlasmidFeature] = {}
    for feature in features:
        key = (feature.feature_type.lower(), feature.label.lower(), feature.intervals, feature.strand)
        previous = merged.get(key)
        if previous is None:
            merged[key] = feature
        else:
            merged[key] = PlasmidFeature(
                feature_id=previous.feature_id,
                feature_type=previous.feature_type,
                label=previous.label,
                intervals=previous.intervals,
                strand=previous.strand,
                sources=tuple(sorted(set(previous.sources + feature.sources))),
                protected=previous.protected or feature.protected,
                feature_class=previous.feature_class,
            )
    return tuple(sorted(merged.values(), key=lambda x: (x.start, x.end, x.label.lower())))


def _read_fasta_sequence(path: Path) -> str:
    return str(SeqIO.read(path, "fasta").seq).upper()


def _record_from_bytes(payload: bytes, fmt: str) -> Any:
    suffix = ".dna" if fmt == "snapgene" else ".gb"
    with tempfile.NamedTemporaryFile(suffix=suffix) as handle:
        handle.write(payload)
        handle.flush()
        return SeqIO.read(handle.name, fmt)


def _snapgene_url(spec: Mapping[str, str]) -> str:
    query = urllib.parse.urlencode({"set": spec["set"], "plasmid": spec["plasmid"]})
    return f"https://www.snapgene.com/local/fetch.php?{query}"


def _ncbi_url(accession: str) -> str:
    return (
        "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?"
        + urllib.parse.urlencode({"db": "nuccore", "id": accession, "rettype": "gbwithparts", "retmode": "text"})
    )


def build_plasmid_reference(
    output: str | Path | None = None,
    *,
    plasmid_fasta_dir: str | Path | None = None,
    include_ncbi: bool = True,
) -> PlasmidReferenceDatabase:
    """Download, verify and reduce public records to the versioned database."""
    root = ProjectPaths.discover().root
    fasta_dir = Path(plasmid_fasta_dir or root / "data" / "reference_input" / "plasmids")
    downloaded_at = utc_now()
    references: list[PlasmidReference] = []
    for reference_id, spec in REFERENCE_SPECS.items():
        expected = _read_fasta_sequence(fasta_dir / spec["fasta"])
        sources: list[PlasmidSource] = []
        normalized: list[PlasmidFeature] = []
        snapgene_url = _snapgene_url(spec)
        snapgene_payload = _download(snapgene_url)
        snapgene_record = _record_from_bytes(snapgene_payload, "snapgene")
        observed = str(snapgene_record.seq).upper()
        if observed != expected:
            raise ValueError(f"SnapGene sequence mismatch for {reference_id}")
        sources.append(PlasmidSource("SnapGene", spec["plasmid"], snapgene_url, downloaded_at, _sha256_bytes(snapgene_payload)))
        normalized.extend(_normalize_record_features(snapgene_record, "SnapGene"))
        accession = spec.get("ncbi", "")
        if include_ncbi and accession:
            ncbi_url = _ncbi_url(accession)
            ncbi_payload = _download(ncbi_url)
            ncbi_record = _record_from_bytes(ncbi_payload, "genbank")
            if str(ncbi_record.seq).upper() != expected:
                raise ValueError(f"NCBI sequence mismatch for {reference_id}/{accession}")
            sources.append(PlasmidSource("NCBI", accession, ncbi_url, downloaded_at, _sha256_bytes(ncbi_payload)))
            normalized.extend(_normalize_record_features(ncbi_record, "NCBI"))
        references.append(
            PlasmidReference(
                reference_id=reference_id,
                display_name=reference_id,
                sequence=expected,
                sequence_sha256=_sha256_sequence(expected),
                circular=True,
                features=_merge_features(normalized),
                sources=tuple(sources),
            )
        )
    profiles = tuple(PlasmidProfile(**spec) for spec in PROFILE_SPECS)
    provisional = PlasmidReferenceDatabase(PLASMID_REFERENCE_VERSION, downloaded_at, tuple(references), profiles, ())
    schemes = tuple(scheme for profile in profiles for scheme in derive_four_cut_schemes(provisional, profile.profile_id))
    database = PlasmidReferenceDatabase(PLASMID_REFERENCE_VERSION, downloaded_at, tuple(references), profiles, schemes)
    validate_plasmid_reference(database, fasta_dir)
    if output is not None:
        write_plasmid_reference(database, output)
    return database


def _reverse_complement(sequence: str) -> str:
    return str(Seq(sequence).reverse_complement())


def _oriented_coordinates(start: int, end: int, length: int, strand: int) -> tuple[int, int]:
    return (start, end) if strand == 1 else (length - end, length - start)


def cutter_is_strictly_inside_mcs(
    database: PlasmidReferenceDatabase,
    profile_id: str,
    cutter: CutterSite,
) -> bool:
    """Return whether a declared inside cutter and both cuts lie in the MCS.

    Recognition-site overlap alone is insufficient for the active exact-DNA
    designer: a Type-IIS-like geometry can recognize bases in the MCS while
    cutting outside it.  Coordinates are compared in expression orientation,
    matching the cut-scheme derivation code.
    """
    if cutter.location != "inside":
        return False
    profile = database.profile(profile_id)
    reference = database.reference(profile.reference_id)
    mcs_start, mcs_end = _oriented_coordinates(
        profile.mcs_start,
        profile.mcs_end,
        len(reference.sequence),
        profile.expression_strand,
    )
    return (
        mcs_start <= int(cutter.oriented_start)
        and int(cutter.oriented_end) <= mcs_end
        and mcs_start <= int(cutter.top_cut_oriented) <= mcs_end
        and mcs_start <= int(cutter.bottom_cut_oriented) <= mcs_end
    )


def _physical_coordinates(start: int, end: int, length: int, strand: int) -> tuple[int, int]:
    return (start, end) if strand == 1 else (length - end, length - start)


def _iter_occurrences(sequence: str, motif: str) -> Iterable[int]:
    motifs = {motif.upper(), _reverse_complement(motif.upper())}
    extended = sequence.upper() + sequence.upper()[: max(len(motif) - 1, 0)]
    found: set[int] = set()
    for candidate in motifs:
        offset = extended.find(candidate)
        while offset >= 0:
            if offset < len(sequence):
                found.add(offset)
            offset = extended.find(candidate, offset + 1)
    yield from sorted(found)


def _enzyme_geometry(name: str) -> tuple[str, int, int, int] | None:
    enzyme = getattr(Restriction, name, None)
    if enzyme is None:
        return None
    site = str(getattr(enzyme, "site", "")).upper()
    if not site or any(base not in "ACGT" for base in site):
        return None
    fst5 = getattr(enzyme, "fst5", None)
    fst3 = getattr(enzyme, "fst3", None)
    overhang = int(getattr(enzyme, "ovhg", 0) or 0)
    if fst5 is None or fst3 is None or overhang == 0:
        return None
    return site, int(fst5), int(fst3), overhang


def _canonical_alias(aliases: Sequence[str], preferred: str) -> str:
    if preferred in aliases:
        return preferred
    neb = [name for name in aliases if "N" in tuple(getattr(getattr(Restriction, name), "suppl", ()))]
    return sorted(neb or list(aliases))[0]


def _candidate_cutter_sites(reference: PlasmidReference, profile: PlasmidProfile) -> list[CutterSite]:
    length = len(reference.sequence)
    oriented = reference.sequence if profile.expression_strand == 1 else _reverse_complement(reference.sequence)
    mcs_start, mcs_end = _oriented_coordinates(profile.mcs_start, profile.mcs_end, length, profile.expression_strand)
    preferred = {profile.legacy_left_enzyme, profile.legacy_right_enzyme}
    grouped: dict[tuple[str, int, int, int], list[str]] = {}
    for enzyme in Restriction.CommOnly:
        name = str(enzyme)
        geometry = _enzyme_geometry(name)
        if geometry is not None:
            grouped.setdefault(geometry, []).append(name)
    rows: list[CutterSite] = []
    for (site, fst5, fst3, overhang), aliases in grouped.items():
        starts = list(_iter_occurrences(oriented, site))
        outside_count = sum(not (start < mcs_end and start + len(site) > mcs_start) for start in starts)
        if outside_count > 1:
            continue
        canonical = _canonical_alias(aliases, next((name for name in preferred if name in aliases), ""))
        for start in starts:
            end = start + len(site)
            # Do not use recognition sites that wrap the chosen MCS boundary.
            if end > length:
                continue
            if start < mcs_end and end > mcs_start:
                location = "inside"
                side = "left" if abs(start - mcs_start) <= abs(end - mcs_end) else "right"
            else:
                # On a circular molecule an external site beyond coordinate 0
                # can be the closest downstream site of an MCS near the end of
                # the oriented sequence (and conversely upstream).  Assign the
                # side by directed circular distance, not raw coordinates.
                left_distance = (mcs_start - end) % length
                right_distance = (start - mcs_end) % length
                location = "outside"
                side = "left" if left_distance <= right_distance else "right"
            pstart, pend = _physical_coordinates(start, end, length, profile.expression_strand)
            rows.append(
                CutterSite(
                    side=side,
                    location=location,
                    canonical_enzyme=canonical,
                    enzyme_aliases=tuple(sorted(aliases)),
                    recognition_site=site,
                    oriented_start=start,
                    oriented_end=end,
                    physical_start=pstart,
                    physical_end=pend,
                    top_cut_oriented=(start + fst5) % length,
                    bottom_cut_oriented=(start + len(site) + fst3) % length,
                    overhang_length=overhang,
                    outside_mcs_occurrences=outside_count,
                )
            )
    return rows


def _pick_boundary_site(
    sites: Sequence[CutterSite], side: str, location: str, mcs_start: int, mcs_end: int, preferred: str
) -> CutterSite | None:
    candidates = [row for row in sites if row.side == side and row.location == location]
    if not candidates:
        return None
    edge = mcs_start if side == "left" else mcs_end
    return min(
        candidates,
        key=lambda row: (
            min(abs(row.oriented_start - edge), abs(row.oriented_end - edge)),
            0 if preferred in row.enzyme_aliases else 1,
            row.canonical_enzyme,
        ),
    )


def _arc(sequence: str, start: int, end: int) -> str:
    return sequence[start:end] if start <= end else sequence[start:] + sequence[:end]


def derive_four_cut_schemes(database: PlasmidReferenceDatabase, profile_id: str) -> tuple[VectorCutScheme, ...]:
    profile = database.profile(profile_id)
    reference = database.reference(profile.reference_id)
    length = len(reference.sequence)
    oriented = reference.sequence if profile.expression_strand == 1 else _reverse_complement(reference.sequence)
    mcs_start, mcs_end = _oriented_coordinates(profile.mcs_start, profile.mcs_end, length, profile.expression_strand)
    sites = _candidate_cutter_sites(reference, profile)
    selected = {
        ("left", location): _pick_boundary_site(sites, "left", location, mcs_start, mcs_end, profile.legacy_left_enzyme)
        for location in ("inside", "outside")
    }
    selected.update({
        ("right", location): _pick_boundary_site(sites, "right", location, mcs_start, mcs_end, profile.legacy_right_enzyme)
        for location in ("inside", "outside")
    })
    results: list[VectorCutScheme] = []
    for left_location, right_location in (("inside", "inside"), ("inside", "outside"), ("outside", "inside"), ("outside", "outside")):
        left = selected[("left", left_location)]
        right = selected[("right", right_location)]
        scheme_name = f"{left_location}/{right_location}"
        invalid = ""
        retained = removed = left_restore = right_restore = ""
        if left is None or right is None:
            invalid = "missing_boundary_cutter"
        else:
            removed = _arc(oriented, left.top_cut_oriented, right.top_cut_oriented)
            retained = _arc(oriented, right.top_cut_oriented, left.top_cut_oriented)
            mcs_midpoint = (mcs_start + (mcs_end - mcs_start) // 2) % length
            cut_span = (right.top_cut_oriented - left.top_cut_oriented) % length
            midpoint_span = (mcs_midpoint - left.top_cut_oriented) % length
            if midpoint_span > cut_span:
                invalid = "cut_arc_does_not_contain_mcs"
            elif len(removed) >= len(retained):
                invalid = "mcs_arc_is_not_short_arc"
            if left_location == "outside":
                left_restore = _arc(oriented, left.top_cut_oriented, mcs_start)
            if right_location == "outside":
                right_restore = _arc(oriented, mcs_end, right.top_cut_oriented)
        results.append(
            VectorCutScheme(
                scheme_id=f"{profile_id}:{scheme_name}",
                profile_id=profile_id,
                left_location=left_location,
                right_location=right_location,
                left_cutter=left,
                right_cutter=right,
                valid=not invalid,
                invalid_reason=invalid,
                retained_backbone_sequence=retained,
                removed_arc_sequence=removed,
                left_restoration_sequence=left_restore,
                right_restoration_sequence=right_restore,
                retained_backbone_sha256=_sha256_sequence(retained) if retained else "",
            )
        )
    return tuple(results)


def _feature_overlap(feature: PlasmidFeature, start: int, end: int) -> bool:
    return any(a < end and b > start for a, b in feature.intervals)


def decide_cutter_silencing(
    database: PlasmidReferenceDatabase,
    profile_id: str,
    cutter: CutterSite,
    *,
    junction_destroyed: bool = False,
) -> SilencingDecision:
    """Apply the strict MCS/feature/stop-codon silencing policy."""
    if junction_destroyed:
        return SilencingDecision(cutter.side, True, "junction_destroyed", "Recognition site is absent after ligation")
    profile = database.profile(profile_id)
    reference = database.reference(profile.reference_id)
    # MCS is an explicit exception even if another broad feature spans it.
    inside_mcs = cutter.physical_start >= profile.mcs_start and cutter.physical_end <= profile.mcs_end
    if inside_mcs:
        return SilencingDecision(cutter.side, True, "mcs_donor_silencing", "MCS bases are donor-provided and may be changed")
    overlaps = tuple(
        sorted(
            {f"{feature.feature_class}:{feature.label}" for feature in reference.features if feature.protected and _feature_overlap(feature, cutter.physical_start, cutter.physical_end)}
        )
    )
    has_stop = any(value.startswith("stop_codon:") for value in overlaps)
    stop_context_only = has_stop and all(
        value.startswith("stop_codon:") or value.startswith("cds:") for value in overlaps
    )
    if stop_context_only:
        return SilencingDecision(
            cutter.side,
            True,
            "stop_rescue_then_silence",
            "Insert an in-frame stop immediately after the final sense codon before disrupting the original stop-containing site",
            overlaps,
            True,
            "TAA",
        )
    if overlaps:
        return SilencingDecision(cutter.side, False, "protected_feature", "Cutter overlaps a protected functional annotation", overlaps)
    return SilencingDecision(cutter.side, True, "donor_only_silencing", "No protected feature overlaps the donor-provided recognition site")


def retained_backbone_contains_site(scheme: VectorCutScheme, recognition_site: str) -> bool:
    if not scheme.valid:
        return True
    motif = str(recognition_site).upper()
    sequence = scheme.retained_backbone_sequence.upper()
    return motif in sequence or _reverse_complement(motif) in sequence


def write_plasmid_reference(database: PlasmidReferenceDatabase, output: str | Path) -> None:
    payload = asdict(database)
    write_json_atomic(payload, output)
    import pandas as pd

    scheme_path = Path(output).with_name(PLASMID_SCHEME_FILENAME)
    rows = []
    for scheme in database.schemes:
        row: dict[str, Any] = {
            "schema_version": database.schema_version,
            "scheme_id": scheme.scheme_id,
            "profile_id": scheme.profile_id,
            "left_location": scheme.left_location,
            "right_location": scheme.right_location,
            "valid": scheme.valid,
            "invalid_reason": scheme.invalid_reason,
            "left_restoration_sequence": scheme.left_restoration_sequence,
            "right_restoration_sequence": scheme.right_restoration_sequence,
            "retained_backbone_sha256": scheme.retained_backbone_sha256,
        }
        for side in ("left", "right"):
            cutter = getattr(scheme, f"{side}_cutter")
            row.update({
                f"{side}_enzyme": cutter.canonical_enzyme if cutter else "",
                f"{side}_enzyme_aliases": ",".join(cutter.enzyme_aliases) if cutter else "",
                f"{side}_recognition_site": cutter.recognition_site if cutter else "",
                f"{side}_physical_start_0based": cutter.physical_start if cutter else None,
                f"{side}_physical_end_0based_exclusive": cutter.physical_end if cutter else None,
                f"{side}_top_cut_oriented": cutter.top_cut_oriented if cutter else None,
                f"{side}_bottom_cut_oriented": cutter.bottom_cut_oriented if cutter else None,
            })
        rows.append(row)
    pd.DataFrame(rows).to_csv(scheme_path, index=False)


def _feature_from_dict(payload: Mapping[str, Any]) -> PlasmidFeature:
    return PlasmidFeature(
        **{
            **payload,
            "intervals": tuple(tuple(int(value) for value in item) for item in payload["intervals"]),
            "sources": tuple(payload["sources"]),
        }
    )


def _cutter_from_dict(payload: Mapping[str, Any] | None) -> CutterSite | None:
    return None if payload is None else CutterSite(**{**payload, "enzyme_aliases": tuple(payload["enzyme_aliases"])})


def load_plasmid_reference(path: str | Path | None = None) -> PlasmidReferenceDatabase:
    payload = json.loads(Path(path or bundled_plasmid_reference_path()).read_text())
    if payload.get("schema_version") != PLASMID_REFERENCE_VERSION:
        raise ValueError(f"Unsupported plasmid reference schema: {payload.get('schema_version')!r}")
    references = tuple(
        PlasmidReference(
            **{
                **row,
                "features": tuple(_feature_from_dict(item) for item in row["features"]),
                "sources": tuple(PlasmidSource(**item) for item in row["sources"]),
            }
        )
        for row in payload["references"]
    )
    profiles = tuple(PlasmidProfile(**row) for row in payload["profiles"])
    schemes = tuple(
        VectorCutScheme(
            **{
                **row,
                "left_cutter": _cutter_from_dict(row.get("left_cutter")),
                "right_cutter": _cutter_from_dict(row.get("right_cutter")),
            }
        )
        for row in payload["schemes"]
    )
    return PlasmidReferenceDatabase(payload["schema_version"], payload["generated_at"], references, profiles, schemes)


def validate_plasmid_reference(
    database: PlasmidReferenceDatabase,
    plasmid_fasta_dir: str | Path | None = None,
) -> dict[str, Any]:
    root = ProjectPaths.discover().root
    fasta_dir = Path(plasmid_fasta_dir or root / "data" / "reference_input" / "plasmids")
    if len(database.references) != 7 or len(database.profiles) != 8:
        raise ValueError("Expected seven physical references and eight profiles")
    for reference in database.references:
        expected = _read_fasta_sequence(fasta_dir / REFERENCE_SPECS[reference.reference_id]["fasta"])
        if reference.sequence != expected or reference.sequence_sha256 != _sha256_sequence(expected):
            raise ValueError(f"Bundled FASTA mismatch for {reference.reference_id}")
    for profile in database.profiles:
        if not any(feature.feature_class == "mcs" for feature in database.reference(profile.reference_id).features):
            raise ValueError(f"No MCS annotation for {profile.profile_id}")
        schemes = database.schemes_for(profile.profile_id)
        if len(schemes) != 4:
            raise ValueError(f"Expected four retained cut schemes for {profile.profile_id}")
    return {
        "schema_version": database.schema_version,
        "physical_reference_count": len(database.references),
        "profile_count": len(database.profiles),
        "scheme_count": len(database.schemes),
        "valid_scheme_count": sum(item.valid for item in database.schemes),
        "shared_pet28_sequence": database.reference("pET-28a(+)").sequence_sha256,
    }
